### PR TITLE
Use `path.dirname` to more safely check for the root directory of the filesystem across platforms

### PR DESCRIPTION
**Pull request by indexzero**
Supersedes #22. cc/ @dotob

### CODE REVIEW

**Comment by dotob** [comment]
hi, thanks for the quick reply. unfortunately in this case an error occurs. and it does not work. so yes in my version it is a non error.

**Comment by indexzero** [comment]
Why is catching this error not an option? 

The error itself is a meaningful semantically: it indicates that a `package.json` file could not be found after traversing up the entire directory structure.

**Comment by dotob** [comment]
pobably you are right. i will make a pr for args too.  so the error is handled there. 

...

**Comment by dotob** [comment]
hi, will you merge this and make a new version? would be awesome. also have an open pr in args.

**Comment by indexzero** [comment]
Done. Released as `pkginfo@0.4.1`

**Pull request merged**
